'use client';

/**
 * <MorningBriefCard> — today's narrative brief at the top of Home.
 *
 * Renders nothing until /api/briefs/today returns content. Once it
 * does, the card sits above every other Home section as the first
 * thing the user sees in the morning. Click anywhere → expands to
 * show all bullets + the suggested focus + a one-tap link to the
 * dashboard.
 *
 * The brief is generated by a daily job at 06:00 UTC. If the user
 * arrives before then (or has no pulse entries), this component
 * renders nothing — Home keeps its existing layout.
 */

import { useState, useEffect, useCallback } from 'react';
import {
  Sparkles, ChevronDown, ChevronUp, ArrowRight, AlertCircle, TrendingUp, TrendingDown, Minus,
} from 'lucide-react';
import api from '@/lib/api';
import { formatRelative } from '@/lib/dates';

interface BriefBullet {
  kind: 'movement' | 'steady' | 'warn';
  label: string;
  delta: string;
  detail: string;
}

interface BriefContent {
  summary: string;
  bullets: BriefBullet[];
  suggested_focus: string;
  confidence: 'high' | 'medium' | 'low';
}

interface Brief {
  id: number;
  brief_date: string;
  content: BriefContent;
  opened_at: string | null;
  emailed_at: string | null;
  created_at: string;
}

export default function MorningBriefCard() {
  const [brief, setBrief] = useState<Brief | null>(null);
  const [loading, setLoading] = useState(true);
  const [expanded, setExpanded] = useState(true);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.get('/briefs/today');
      setBrief(res.data.data ?? null);
    } catch {
      setBrief(null);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const markOpened = useCallback(async () => {
    if (!brief || brief.opened_at) return;
    try { await api.post(`/briefs/${brief.id}/opened`); } catch { /* ignore */ }
  }, [brief]);

  // Mark opened the first time the user expands or visits — best-effort.
  useEffect(() => {
    if (brief && !brief.opened_at && expanded) {
      void markOpened();
    }
  }, [brief, expanded, markOpened]);

  if (loading) return null;
  if (!brief) return null;

  const c = brief.content;
  const briefAge = brief.created_at ? formatRelative(new Date(brief.created_at)) : 'today';

  return (
    <section className="bg-gradient-to-br from-ocean/[0.04] to-transparent border border-ocean/20 rounded-md overflow-hidden">
      {/* Header — always visible. */}
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full px-5 py-3.5 flex items-start justify-between gap-4 text-left hover:bg-ocean/[0.02] transition-colors"
      >
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 mb-1.5">
            <Sparkles className="w-4 h-4 text-ocean" strokeWidth={1.75} />
            <span className="text-[10.5px] font-mono uppercase tracking-[0.14em] text-ocean">
              Today&rsquo;s brief
            </span>
            <span className="text-[10.5px] font-mono uppercase tracking-[0.1em] text-muted-2">
              {briefAge}
            </span>
            {!brief.opened_at && (
              <span className="px-1.5 py-0.5 text-[9.5px] font-mono uppercase tracking-[0.1em] bg-ocean text-on-ocean rounded">
                New
              </span>
            )}
            {c.confidence === 'low' && (
              <span className="px-1.5 py-0.5 text-[9.5px] font-mono uppercase tracking-[0.1em] bg-amber-50 text-amber-700 border border-amber-200 rounded">
                Low confidence
              </span>
            )}
          </div>
          <p className="font-display text-[16.5px] leading-[1.45] text-ink m-0">
            {c.summary}
          </p>
        </div>
        <div className="flex-shrink-0 mt-0.5 text-muted hover:text-ink">
          {expanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </div>
      </button>

      {/* Body — bullets + suggested focus. */}
      {expanded && (
        <div className="border-t border-ocean/15 bg-bg/40">
          {c.bullets.length > 0 && (
            <ul className="divide-y divide-ocean/10">
              {c.bullets.map((b, i) => (
                <li key={i} className="px-5 py-3 flex items-start gap-3">
                  <BulletIcon kind={b.kind} delta={b.delta} />
                  <div className="flex-1 min-w-0">
                    <div className="flex items-baseline gap-2">
                      <span className="text-[13px] font-medium text-ink">{b.label}</span>
                      <span className={`text-[11.5px] font-mono ${deltaColour(b.kind, b.delta)}`}>
                        {b.delta}
                      </span>
                    </div>
                    <p className="text-[12.5px] text-ink-2 leading-relaxed mt-0.5">{b.detail}</p>
                  </div>
                </li>
              ))}
            </ul>
          )}

          {c.suggested_focus && (
            <div className="px-5 py-3 border-t border-ocean/15 bg-ocean/[0.04] flex items-start gap-3">
              <ArrowRight className="w-3.5 h-3.5 mt-1 text-ocean flex-shrink-0" strokeWidth={1.75} />
              <div className="flex-1 min-w-0">
                <div className="text-[10.5px] font-mono uppercase tracking-[0.1em] text-ocean mb-0.5">
                  Suggested focus
                </div>
                <p className="font-display italic text-[14px] text-ink leading-snug m-0">
                  {c.suggested_focus}
                </p>
              </div>
            </div>
          )}
        </div>
      )}
    </section>
  );
}

// ───────────────────────────────────────────────────────────────────────────
// Visual atoms
// ───────────────────────────────────────────────────────────────────────────

function BulletIcon({ kind, delta }: { kind: BriefBullet['kind']; delta: string }) {
  if (kind === 'warn') {
    return (
      <span className="flex-shrink-0 mt-1 w-5 h-5 rounded-full bg-amber-50 border border-amber-200 flex items-center justify-center">
        <AlertCircle className="w-3 h-3 text-amber-600" strokeWidth={1.75} />
      </span>
    );
  }
  if (kind === 'steady') {
    return (
      <span className="flex-shrink-0 mt-1 w-5 h-5 rounded-full bg-soft border border-line flex items-center justify-center">
        <Minus className="w-3 h-3 text-muted" strokeWidth={1.75} />
      </span>
    );
  }
  // movement — direction from delta string
  const isUp = !delta.trim().startsWith('-') && !delta.trim().startsWith('−');
  const Icon = isUp ? TrendingUp : TrendingDown;
  const colour = isUp ? 'text-emerald-600 bg-emerald-50 border-emerald-200'
                       : 'text-red-600 bg-red-50 border-red-200';
  return (
    <span className={`flex-shrink-0 mt-1 w-5 h-5 rounded-full border flex items-center justify-center ${colour}`}>
      <Icon className="w-3 h-3" strokeWidth={1.75} />
    </span>
  );
}

function deltaColour(kind: BriefBullet['kind'], delta: string): string {
  if (kind === 'warn') return 'text-amber-700';
  if (kind === 'steady') return 'text-muted-2';
  const isUp = !delta.trim().startsWith('-') && !delta.trim().startsWith('−');
  return isUp ? 'text-emerald-700' : 'text-red-600';
}
