/**
 * Operator script — list and delete tenants.
 *
 * Multi-tenancy is enforced by Postgres RLS, so the product UI never
 * shows you (the operator) any tenant other than your own. This script
 * is the back door: connect with the admin DB role, run privileged
 * queries, and present a cross-tenant view.
 *
 * Usage:
 *
 *   # List all tenants with row counts
 *   DATABASE_URL='postgresql://databridge:...@host/databridge?sslmode=require' \
 *     npx ts-node scripts/admin-tenants.ts list
 *
 *   # Show details of one tenant (users, connections, products, age)
 *   DATABASE_URL=... npx ts-node scripts/admin-tenants.ts show 4
 *
 *   # Delete a tenant and ALL its data (irreversible — prompts confirm)
 *   DATABASE_URL=... npx ts-node scripts/admin-tenants.ts delete 4
 *
 *   # Delete the smoke-test tenant (matches email pattern, idempotent)
 *   DATABASE_URL=... npx ts-node scripts/admin-tenants.ts delete-smoke-test
 *
 * Requires the admin DB role (not databridge_app) because deletion
 * cascades across tables some of which have RLS.
 *
 * Confirmation prompt is bypassed with --yes for automation.
 */
import { Client } from 'pg';
import * as readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';

// Every tenant-scoped table — the script deletes from each in dependency
// order so foreign keys are respected. Generated by listing every table
// with a tenant_id column at runtime; keeps the script future-proof.
async function listTenantTables(client: Client): Promise<string[]> {
  const r = await client.query<{ table_name: string }>(`
    SELECT t.table_name
      FROM information_schema.columns c
      JOIN information_schema.tables t
        ON t.table_schema = c.table_schema AND t.table_name = c.table_name
     WHERE c.table_schema = 'public'
       AND c.column_name  = 'tenant_id'
       AND t.table_type   = 'BASE TABLE'
     ORDER BY t.table_name
  `);
  return r.rows.map((x) => x.table_name);
}

async function cmdList(client: Client): Promise<void> {
  const tenants = await client.query<{
    id: number; name: string; slug: string; status: string;
    created_at: string;
  }>(`SELECT id, name, slug, status, created_at FROM tenants ORDER BY id`);

  // Per-tenant signal: user / connection / product / source-table counts.
  // Filter explicitly on tenant_id rather than relying on SET app.current_tenant
  // — the admin role has BYPASSRLS so RLS-as-filter doesn't apply here.
  // GROUP BY in a single query is also a lot faster than N round-trips.
  const stats: Record<number, { users: number; conns: number; products: number; tables: number }> = {};
  for (const t of tenants.rows) {
    stats[t.id] = { users: 0, conns: 0, products: 0, tables: 0 };
  }
  for (const [field, table] of [
    ['users',    'users']         as const,
    ['conns',    'connections']   as const,
    ['products', 'data_products'] as const,
    ['tables',   'source_tables'] as const,
  ]) {
    const r = await client.query<{ tenant_id: number; n: string }>(
      `SELECT tenant_id, COUNT(*)::text AS n FROM ${table} GROUP BY tenant_id`,
    );
    for (const row of r.rows) {
      const tid = Number(row.tenant_id);
      if (stats[tid]) (stats[tid] as Record<string, number>)[field] = Number(row.n);
    }
  }

  const fmtDate = (s: string) => {
    const d = new Date(s);
    return Number.isNaN(d.getTime()) ? '?' : d.toISOString().slice(0, 10);
  };

  console.log('');
  console.log('id  status   created    name                              users  conns  prods  srcTbl  slug');
  console.log('──  ───────  ─────────  ────────────────────────────────  ─────  ─────  ─────  ──────  ──────────');
  for (const t of tenants.rows) {
    const s = stats[t.id];
    console.log(
      `${String(t.id).padEnd(3)} ${t.status.padEnd(8)} ${fmtDate(t.created_at).padEnd(10)} ${t.name.slice(0, 32).padEnd(32)}  ` +
      `${String(s.users).padStart(5)}  ${String(s.conns).padStart(5)}  ${String(s.products).padStart(5)}  ${String(s.tables).padStart(6)}  ${t.slug}`,
    );
  }
  console.log('');
  console.log(`Total: ${tenants.rows.length} tenants`);
}

async function cmdShow(client: Client, tenantId: number): Promise<void> {
  await client.query(`SET app.current_tenant = '${tenantId}'`);
  const t = await client.query(`SELECT id, name, slug, status, created_at FROM tenants WHERE id = $1`, [tenantId]);
  if (t.rows.length === 0) {
    console.log(`tenant ${tenantId} not found.`); return;
  }
  console.log(t.rows[0]);
  const u = await client.query(`SELECT id, email, role, is_active, mfa_enabled_at, created_at FROM users ORDER BY id`);
  console.log(`\nUsers (${u.rows.length}):`);
  for (const r of u.rows) console.log(`  ${r.id}  ${r.role.padEnd(8)} ${r.is_active ? 'active' : 'inactive'}  ${r.email}`);

  const c = await client.query(`SELECT id, name, type, created_at FROM connections ORDER BY id`);
  console.log(`\nConnections (${c.rows.length}):`);
  for (const r of c.rows) console.log(`  ${r.id}  ${r.type.padEnd(12)} ${r.name}`);

  const p = await client.query(`SELECT id, name, status FROM data_products ORDER BY id`);
  console.log(`\nData Products (${p.rows.length}):`);
  for (const r of p.rows) console.log(`  ${r.id}  ${(r.status || '?').padEnd(10)} ${r.name}`);
}

async function cmdDelete(client: Client, tenantId: number, confirmed: boolean): Promise<void> {
  const t = await client.query(`SELECT id, name, slug FROM tenants WHERE id = $1`, [tenantId]);
  if (t.rows.length === 0) { console.log(`tenant ${tenantId} not found.`); return; }
  const tn = t.rows[0];

  if (!confirmed) {
    const rl = readline.createInterface({ input, output });
    const answer = await rl.question(
      `\n⚠ This will permanently delete tenant ${tn.id} "${tn.name}" (${tn.slug}) and ALL data: users, connections, source data, products, dashboards, etc.\n` +
      `Type the slug "${tn.slug}" to confirm: `,
    );
    rl.close();
    if (answer.trim() !== tn.slug) { console.log('Aborted.'); return; }
  }

  // Set tenant context so the DELETEs hit the WITH CHECK clauses.
  await client.query(`SET app.current_tenant = '${tenantId}'`);

  const tables = await listTenantTables(client);
  // Delete from each table — order doesn't matter much for tenant scope
  // because every row matches WHERE tenant_id = X, but we wrap in a
  // transaction so a partial failure rolls back cleanly.
  await client.query('BEGIN');
  try {
    let total = 0;
    for (const tbl of tables) {
      const r = await client.query(`DELETE FROM "${tbl}" WHERE tenant_id = $1`, [tenantId]);
      if (r.rowCount && r.rowCount > 0) {
        console.log(`  ${tbl}: ${r.rowCount}`);
        total += r.rowCount;
      }
    }
    // tenants table has no RLS — delete the row itself
    const tr = await client.query(`DELETE FROM tenants WHERE id = $1`, [tenantId]);
    console.log(`  tenants: ${tr.rowCount}`);
    total += tr.rowCount ?? 0;
    await client.query('COMMIT');
    console.log(`\n✓ Deleted tenant ${tn.id} "${tn.name}" — ${total} rows total.`);
    console.log(`Note: any warehouse parquet files for this tenant are NOT yet removed. See backend/src/services/warehouse/deleter.ts for the Azure blob cleanup path; can be wired into this script in a follow-up.`);
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  }
}

async function cmdDeleteSmokeTest(client: Client): Promise<void> {
  const u = await client.query<{ tenant_id: number; email: string }>(`
    SELECT tenant_id, email FROM users
     WHERE email LIKE 'smoke-test-%' OR email LIKE '%@example-invalid.test'
  `);
  if (u.rows.length === 0) { console.log('no smoke-test users found.'); return; }
  console.log(`Found ${u.rows.length} smoke-test user(s):`);
  for (const r of u.rows) console.log(`  tenant=${r.tenant_id}  ${r.email}`);
  const tenantIds = Array.from(new Set(u.rows.map((r) => r.tenant_id)));
  for (const tid of tenantIds) {
    await cmdDelete(client, tid, true);
  }
}

async function main(): Promise<void> {
  const cmd = process.argv[2];
  const arg = process.argv[3];
  const autoYes = process.argv.includes('--yes');
  if (!cmd || !['list', 'show', 'delete', 'delete-smoke-test'].includes(cmd)) {
    console.log('Usage:');
    console.log('  admin-tenants.ts list');
    console.log('  admin-tenants.ts show <tenantId>');
    console.log('  admin-tenants.ts delete <tenantId> [--yes]');
    console.log('  admin-tenants.ts delete-smoke-test');
    process.exit(1);
  }
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error('DATABASE_URL not set');

  const client = new Client({
    connectionString: url,
    ssl: { rejectUnauthorized: false },
    connection_timeout_millis: 10000,
  } as never);
  await client.connect();

  try {
    if (cmd === 'list') await cmdList(client);
    else if (cmd === 'show') {
      if (!arg) throw new Error('tenant id required: show <id>');
      await cmdShow(client, Number(arg));
    } else if (cmd === 'delete') {
      if (!arg) throw new Error('tenant id required: delete <id>');
      await cmdDelete(client, Number(arg), autoYes);
    } else if (cmd === 'delete-smoke-test') {
      await cmdDeleteSmokeTest(client);
    }
  } finally {
    await client.end();
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
