/**
 * Odoo curated core-field descriptions — the Tier-2 FALLBACK beneath the
 * live `fields_get` harvest (docs/SOURCE_ONBOARDING.md).
 *
 * Odoo's field metadata has labels for everything but `help` tooltips only
 * where a developer bothered to write one — many core business fields
 * (partner_id, invoice_date, amount_total, …) ship with none and used to
 * fall through to the AI pipeline. This map fills those gaps with curated
 * descriptions of Odoo's STANDARD data model (Odoo 16+ semantics).
 *
 * Precedence in `buildEntityDocs`: live instance `help` text ALWAYS wins
 * (it reflects the tenant's customisations and language); this map is used
 * only when the instance returns no help; the generic "references …"
 * synthesis for many2one fields is the last resort. Keyed by MODEL name
 * (`account.move`), field → description. Fields absent here and without
 * help still fall back to the AI pipeline — that is expected for custom
 * fields.
 *
 * Hand-curated 2026-07-20 against the Odoo 16/17 standard data model.
 */

export const ODOO_COLUMN_DOCS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  'res.partner': {
    id: 'Technical identifier of the partner record',
    name: 'Name of the person or organisation',
    display_name: 'Full display name including parent company prefix',
    company_id: 'Company (in multi-company setups) this contact belongs to',
    parent_id: 'Parent company of this contact or address',
    is_company: 'True when the record is an organisation rather than an individual',
    customer_rank: 'Greater than zero when the partner has been used as a customer',
    supplier_rank: 'Greater than zero when the partner has been used as a vendor',
    street: 'Street line of the primary address',
    city: 'City of the primary address',
    zip: 'Postal code of the primary address',
    country_id: 'Country of the primary address',
    email: 'Primary e-mail address',
    phone: 'Primary phone number',
    vat: 'Tax / VAT identification number',
    ref: 'Internal reference code for the partner',
    lang: 'Language used in documents sent to this partner',
    active: 'False when the partner has been archived',
    create_date: 'When the record was created',
    write_date: 'When the record was last modified',
  },
  'res.company': {
    id: 'Technical identifier of the company',
    name: 'Legal name of the company',
    currency_id: 'Main currency the company keeps its books in',
    partner_id: 'Partner record holding the company address and contact details',
    create_date: 'When the record was created',
    write_date: 'When the record was last modified',
  },
  'res.currency': {
    id: 'Technical identifier of the currency',
    name: 'ISO currency code (EUR, USD, …)',
    symbol: 'Currency symbol used in amounts',
    rounding: 'Smallest rounding unit for amounts in this currency',
    active: 'False when the currency is disabled',
    write_date: 'When the record was last modified',
  },
  'account.account': {
    id: 'Technical identifier of the general-ledger account',
    name: 'Name of the general-ledger account',
    code: 'Account code in the chart of accounts',
    account_type: 'Account category (receivable, payable, income, expense, …) driving report placement',
    reconcile: 'True when open items on this account are matched (receivable/payable style)',
    company_id: 'Company this account belongs to',
    deprecated: 'True when the account is closed for new entries',
    write_date: 'When the record was last modified',
  },
  'account.journal': {
    id: 'Technical identifier of the journal',
    name: 'Name of the journal',
    code: 'Short code of the journal shown in entry numbers',
    type: 'Journal kind: sale, purchase, bank, cash or general',
    company_id: 'Company this journal belongs to',
    currency_id: 'Currency of the journal when it differs from the company currency',
    write_date: 'When the record was last modified',
  },
  'account.move': {
    id: 'Technical identifier of the journal entry',
    name: 'Document number (e.g. INV/2026/0001)',
    move_type: 'Document kind: customer invoice, credit note, vendor bill, refund or misc entry',
    partner_id: 'Customer or vendor the document belongs to',
    invoice_date: 'Invoice or bill date printed on the document',
    invoice_date_due: 'Date the invoice is due for payment',
    date: 'Accounting date the entry is posted on',
    state: 'Lifecycle state: draft, posted or cancelled',
    payment_state: 'Payment progress: not paid, in payment, paid, partially paid or reversed',
    journal_id: 'Journal the entry is posted in',
    company_id: 'Company the entry belongs to',
    currency_id: 'Currency of the document amounts',
    amount_untaxed: 'Total before taxes, in document currency',
    amount_tax: 'Total tax amount, in document currency',
    amount_total: 'Total including taxes, in document currency',
    amount_residual: 'Amount still open (unpaid), in document currency',
    invoice_origin: 'Source document (e.g. the sales order) the invoice was created from',
    ref: 'External reference, e.g. the vendor bill number',
    invoice_payment_term_id: 'Payment terms applied to this invoice',
    create_date: 'When the record was created',
    write_date: 'When the record was last modified',
  },
  'account.move.line': {
    id: 'Technical identifier of the journal item',
    move_id: 'Journal entry (invoice, bill or misc entry) this line belongs to',
    name: 'Label or product description of the line',
    account_id: 'General-ledger account the line is booked on',
    partner_id: 'Partner the line relates to',
    journal_id: 'Journal of the parent entry',
    company_id: 'Company the line belongs to',
    product_id: 'Product on the line, when it comes from an invoice line',
    quantity: 'Quantity invoiced or booked on the line',
    price_unit: 'Unit price on the line, in document currency',
    price_subtotal: 'Line total before taxes, in document currency',
    price_total: 'Line total including taxes, in document currency',
    debit: 'Debit amount in company currency',
    credit: 'Credit amount in company currency',
    balance: 'Debit minus credit in company currency',
    amount_currency: 'Amount in the document currency when it differs from the company currency',
    currency_id: 'Currency of amount_currency',
    date: 'Accounting date inherited from the parent entry',
    date_maturity: 'Due date of the line for receivables and payables',
    reconciled: 'True when the receivable/payable line is fully matched with payments',
    display_type: 'Line kind: product line, section or note (sections and notes carry no amounts)',
    tax_ids: 'Taxes applied on the line',
    write_date: 'When the record was last modified',
  },
  'account.payment': {
    id: 'Technical identifier of the payment',
    name: 'Payment number',
    payment_type: 'Direction of the payment: inbound (received) or outbound (sent)',
    partner_type: 'Whether the counterparty is a customer or a supplier',
    partner_id: 'Customer or vendor the payment is registered against',
    amount: 'Payment amount in the payment currency',
    currency_id: 'Currency of the payment',
    date: 'Date the payment was registered',
    journal_id: 'Bank or cash journal the payment went through',
    state: 'Lifecycle state of the payment (draft, posted, cancelled)',
    ref: 'Memo / communication of the payment',
    write_date: 'When the record was last modified',
  },
  'account.payment.term': {
    id: 'Technical identifier of the payment term',
    name: 'Name of the payment term (e.g. 30 days end of month)',
    active: 'False when the payment term has been archived',
    write_date: 'When the record was last modified',
  },
  'account.tax': {
    id: 'Technical identifier of the tax',
    name: 'Name of the tax as shown on documents',
    amount: 'Tax rate (percentage) or fixed amount depending on amount_type',
    amount_type: 'How the tax is computed: percentage, fixed, or group',
    type_tax_use: 'Whether the tax applies on sales, purchases or none',
    company_id: 'Company this tax belongs to',
    active: 'False when the tax has been archived',
    write_date: 'When the record was last modified',
  },
  'product.template': {
    id: 'Technical identifier of the product template',
    name: 'Product name',
    default_code: 'Internal reference (SKU) of the product',
    categ_id: 'Product category, driving grouping and accounting defaults',
    type: 'Product kind: storable good, consumable or service',
    list_price: 'Default sales price before pricelists',
    standard_price: 'Cost of the product used for valuation and margins',
    uom_id: 'Default unit of measure for sales and stock',
    uom_po_id: 'Default unit of measure for purchasing',
    active: 'False when the product has been archived',
    sale_ok: 'True when the product can be sold',
    purchase_ok: 'True when the product can be purchased',
    barcode: 'Barcode (EAN/UPC) of the product',
    create_date: 'When the record was created',
    write_date: 'When the record was last modified',
  },
  'product.product': {
    id: 'Technical identifier of the product variant',
    product_tmpl_id: 'Product template this variant belongs to',
    default_code: 'Internal reference (SKU) of the variant',
    barcode: 'Barcode (EAN/UPC) of the variant',
    active: 'False when the variant has been archived',
    write_date: 'When the record was last modified',
  },
  'product.category': {
    id: 'Technical identifier of the category',
    name: 'Category name',
    parent_id: 'Parent category in the hierarchy',
    complete_name: 'Full category path (parent / child)',
    write_date: 'When the record was last modified',
  },
  'uom.uom': {
    id: 'Technical identifier of the unit of measure',
    name: 'Unit name (Units, kg, hour, …)',
    category_id: 'UoM category; conversions are only possible within a category',
    factor: 'Conversion factor to the reference unit of the category',
    uom_type: 'Whether this is the reference unit, bigger or smaller than it',
    active: 'False when the unit has been archived',
    write_date: 'When the record was last modified',
  },
  'sale.order': {
    id: 'Technical identifier of the sales order',
    name: 'Order number (e.g. S00042)',
    partner_id: 'Customer the order is for',
    partner_invoice_id: 'Invoice address used for the order',
    partner_shipping_id: 'Delivery address used for the order',
    date_order: 'Date the quotation was created or the order confirmed',
    state: 'Lifecycle state: draft quotation, sent, confirmed sale or cancelled',
    invoice_status: 'Invoicing progress: nothing to invoice, to invoice or fully invoiced',
    amount_untaxed: 'Order total before taxes',
    amount_tax: 'Total tax amount on the order',
    amount_total: 'Order total including taxes',
    currency_id: 'Currency of the order amounts',
    company_id: 'Company the order belongs to',
    user_id: 'Salesperson responsible for the order',
    team_id: 'Sales team the order is attributed to',
    client_order_ref: 'Customer reference for the order',
    create_date: 'When the record was created',
    write_date: 'When the record was last modified',
  },
  'sale.order.line': {
    id: 'Technical identifier of the order line',
    order_id: 'Sales order this line belongs to',
    product_id: 'Product variant sold on this line',
    name: 'Line description as printed on the order',
    product_uom_qty: 'Quantity ordered, in the line unit of measure',
    qty_delivered: 'Quantity already delivered',
    qty_invoiced: 'Quantity already invoiced',
    product_uom: 'Unit of measure of the line quantities',
    price_unit: 'Unit price before discount',
    discount: 'Discount percentage applied on the line',
    price_subtotal: 'Line total before taxes',
    price_total: 'Line total including taxes',
    currency_id: 'Currency of the line amounts',
    state: 'State inherited from the parent order',
    display_type: 'Line kind: product line, section or note (sections and notes carry no amounts)',
    write_date: 'When the record was last modified',
  },
  'purchase.order': {
    id: 'Technical identifier of the purchase order',
    name: 'Order number (e.g. P00021)',
    partner_id: 'Vendor the order is placed with',
    date_order: 'Date the order was created or confirmed',
    date_approve: 'Date the order was approved',
    state: 'Lifecycle state: draft RFQ, sent, confirmed purchase, done or cancelled',
    invoice_status: 'Billing progress: nothing to bill, waiting bills or fully billed',
    amount_untaxed: 'Order total before taxes',
    amount_tax: 'Total tax amount on the order',
    amount_total: 'Order total including taxes',
    currency_id: 'Currency of the order amounts',
    company_id: 'Company the order belongs to',
    user_id: 'Purchase representative responsible for the order',
    partner_ref: 'Vendor reference (their order or quote number)',
    create_date: 'When the record was created',
    write_date: 'When the record was last modified',
  },
  'purchase.order.line': {
    id: 'Technical identifier of the order line',
    order_id: 'Purchase order this line belongs to',
    product_id: 'Product variant purchased on this line',
    name: 'Line description as printed on the order',
    product_qty: 'Quantity ordered, in the line unit of measure',
    qty_received: 'Quantity already received',
    qty_invoiced: 'Quantity already billed',
    product_uom: 'Unit of measure of the line quantities',
    price_unit: 'Unit cost agreed with the vendor',
    price_subtotal: 'Line total before taxes',
    price_total: 'Line total including taxes',
    currency_id: 'Currency of the line amounts',
    state: 'State inherited from the parent order',
    date_planned: 'Expected receipt date for the line',
    write_date: 'When the record was last modified',
  },
  'stock.move': {
    id: 'Technical identifier of the stock move',
    name: 'Description of the move',
    product_id: 'Product variant being moved',
    product_uom_qty: 'Planned quantity to move, in the move unit of measure',
    quantity: 'Quantity actually moved once the move is done',
    product_uom: 'Unit of measure of the move quantities',
    location_id: 'Source location the product leaves',
    location_dest_id: 'Destination location the product enters',
    state: 'Lifecycle state: draft, waiting, assigned, done or cancelled',
    date: 'Date the move was processed (or is scheduled)',
    reference: 'Reference of the transfer document the move belongs to',
    picking_id: 'Transfer (delivery, receipt or internal) grouping this move',
    company_id: 'Company the move belongs to',
    write_date: 'When the record was last modified',
  },
  'stock.quant': {
    id: 'Technical identifier of the quant',
    product_id: 'Product variant the on-hand quantity is for',
    location_id: 'Stock location holding the quantity',
    quantity: 'On-hand quantity in the product unit of measure',
    reserved_quantity: 'Part of the on-hand quantity reserved for outgoing operations',
    company_id: 'Company owning the stock',
    write_date: 'When the record was last modified',
  },
  'stock.valuation.layer': {
    id: 'Technical identifier of the valuation layer',
    product_id: 'Product variant the valuation entry is for',
    quantity: 'Quantity added to or removed from stock by this layer',
    value: 'Monetary value of the layer in company currency',
    unit_cost: 'Unit cost used for this layer',
    stock_move_id: 'Stock move that generated this valuation entry',
    company_id: 'Company the valuation belongs to',
    create_date: 'When the valuation entry was created',
  },
};
