/**
 * AI prompts for Kimball star schema design + SQL generation (single AI call).
 *
 * Optimized for token efficiency: one call produces schema, columns, AND
 * transformation SQL. dim_date is auto-injected by the runner (never AI-generated).
 *
 * Recommended thinking budget: 4000 tokens.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ColumnLineage {
  source_table_name: string;
  source_column_name: string;
  transformation_description: string;
}

export interface ColumnDesign {
  column_name: string;
  data_type: string;
  display_name: string;
  description: string;
  column_role: 'surrogate_key' | 'natural_key' | 'foreign_key' | 'measure' | 'attribute' | 'degenerate_dimension';
  fk_target_table?: string;
  fk_target_column?: string;
  /**
   * When TRUE, this column is technical/infrastructure and must never
   * surface in end-user output (chat results, narratives, default sample
   * previews). It remains available for JOINs in NL→SQL.
   *
   * AI should set TRUE for:
   *   - UUID/GUID-shaped FK columns (account_id from a source like EO,
   *     where the user knows accounts by name, not by GUID)
   *   - Surrogate FK keys (`customer_key`, `account_key`) in facts
   *   - Internal infrastructure (`_row_hash`, etc.)
   *
   * AI should set FALSE for:
   *   - Business identifiers (invoice_number, sku, customer_code)
   *   - All measures, attributes, dates
   */
  is_technical?: boolean;
  transformation_expression: string;
  additivity?: 'additive' | 'semi_additive' | 'non_additive';
  scd_type: number;
  sort_order: number;
  lineage: ColumnLineage[];
}

export interface TableDesign {
  table_name: string;
  display_name: string;
  description: string;
  table_role: 'fact' | 'dimension' | 'bridge' | 'junk';
  dag_order: number;
  transformation_sql?: string;
  columns: ColumnDesign[];
}

export interface RelationshipDesign {
  from_table_name: string;
  from_column_name: string;
  to_table_name: string;
  to_column_name: string;
  relationship_type: 'fact_to_dim' | 'dim_to_dim';
}

export interface StarSchemaDesign {
  name: string;
  description: string;
  grain: string;
  fact_table_type: 'transaction' | 'periodic_snapshot' | 'accumulating_snapshot' | 'factless';
  tables: TableDesign[];
  relationships: RelationshipDesign[];
}

export interface ProposedKpi {
  name: string;
  description: string;
  formula_plain_text: string;
  formula_sql: string;
  additivity: string;
}

/** Output from the combined design + SQL call. */
export interface StarSchemaDesignOutput {
  star_schema: StarSchemaDesign;         // singular — exactly 1 schema per product
  proposed_kpis: ProposedKpi[];
  dim_date_range: { start: string; end: string };
}

// Legacy compat — callers that still reference star_schemas (array) can adapt
export type { StarSchemaDesignOutput as StarSchemaDesignResult };

// ---------------------------------------------------------------------------
// Prompt — Combined Star Schema Design + Transformation SQL
// ---------------------------------------------------------------------------

export function STAR_SCHEMA_DESIGN_SYSTEM(semanticContext: string, currentDate: string): string {
  return `You are an expert Kimball star schema architect and DuckDB SQL engineer. Design a star schema AND generate the DuckDB SQL to materialize it — in a single response.

Current date: ${currentDate}

━━━ SOURCE SCHEMA (use ONLY these exact column names — character for character) ━━━

${semanticContext}

━━━ CRITICAL: COLUMN NAME RULES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

- Use ONLY the exact column names listed above. NEVER translate, expand, or abbreviate.
- If source has "artikelnr", write "artikelnr" — NOT "artikelnummer" or "article_number".
- If source has "naam", write "naam" — NOT "name" or "naam_nl".
- If source has "groep_id", write "groep_id" — NOT "artikelgroep_id" or "group_id".
- Copy every column name character-for-character. Any deviation causes a runtime crash.

━━━ STRUCTURAL CONSTRAINTS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

- Design exactly ONE star schema. Usually 1 fact table; 2-3 facts allowed when the
  data product genuinely covers multiple related business processes (e.g. orders + invoices).
- Maximum 10 tables total (facts + dimensions + junk/bridge).
- Each dimension appears ONLY ONCE — multiple facts share the same dimension tables.
- At most 1 junk dimension to group all low-cardinality flags/indicators.
- Do NOT include dim_date — it is auto-generated by the system.
  But DO reference it: fact table FKs should point to dim_date.date_key.
  In fact SQL, compute date keys as: TRY_CAST(strftime(TRY_CAST(date_col AS DATE), '%Y%m%d') AS INTEGER)
  Use COALESCE(..., -1) for nullable dates.

━━━ PRODUCT KIND (analytics vs reference) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The catalog now classifies every data product as either ANALYTICS or REFERENCE.
You are designing an ANALYTICS product — one that has at least one fact table
and produces measurable business outcomes (Sales, Procurement, Inventory).

DO NOT:
- Produce a product called "Reference", "Master data", "Dimensions", or any
  variant of a catch-all wrapper. These names became the legacy bucketing that
  the new catalog explicitly fixes.
- Bundle dimensions that aren't joined to a fact in this design into the
  product. Loose dims belong as their own reference products (designed
  separately when needed); they don't ride along with an analytics design.
- Include a dim that has no FK from any fact in this design. If a dim isn't
  joined to a fact here, drop it — it doesn't belong.

DO:
- Name the product after the business process or capability ("Sales",
  "Procurement & Inventory", "Customer engagement"). Never after the storage
  shape or contents.
- Keep the product tight: one process, the facts that measure it, and the
  dims those facts join to. Cohesion over completeness.

━━━ KIMBALL METHODOLOGY ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Four-step design process:**

1. **Grain** — for each fact table, declare the lowest-granularity business event ("One row per ...").
   Every column in the fact must be true to that grain. Document in each fact table's description.
   The top-level grain field describes the primary fact table's grain.

2. **Fact table type:**
   - Transaction: discrete events at a point in time
   - Periodic snapshot: status at regular intervals (daily/monthly)
   - Accumulating snapshot: process with multiple milestone dates
   - Factless: event with no numeric measure

3. **Dimensions** — for each fact, ask "who, what, where, when, how, why?"
   - Date/time (always — via auto-generated dim_date)
   - Entity dims: customer, product, supplier, employee, location, etc.
   - Junk dim: group all low-cardinality flags into one table
   - Degenerate dims: transaction/document numbers stay in the fact as plain columns

4. **Measures** — classify every numeric column:
   - Additive: can be summed across all dimensions (revenue, quantity, cost)
   - Semi-additive: sum across some dims, not time (balance, headcount)
   - Non-additive: cannot sum (unit price, ratio, percentage)
   For ratios: store numerator + denominator as additive columns; derive ratio in BI layer.

**Key rules:**
- Surrogate keys: every dim gets {entity}_key as INTEGER via ROW_NUMBER(). Keep natural key too.
- FKs in facts: named to match target dim's surrogate key. Use COALESCE(dim_key, -1) for unknowns.
- Denormalize lookups: fold classification/lookup tables into their parent dimension (customer_groups → dim_customer, product_categories → dim_product). Only separate if the lookup has its own independent facts.
- Flatten hierarchies: no snowflaking — one flat dimension table per entity.
- SCD: default Type 1 (overwrite). Only use Type 2 if there's a confirmed need for history.
- Role-playing dims: when one dim appears multiple times (order_date, ship_date), create FK aliases all pointing to dim_date.
- Bridge tables: only for true many-to-many relationships.
- Never place text attributes in fact tables — move them to dimensions.
- Never leave NULL FKs in facts — use surrogate -1.

**Naming:**
- Tables: fact_{process}, dim_{entity}, dim_{fact}_junk, bridge_{rel}
- Surrogate keys: {entity}_key
- FKs: match the target dimension's key name exactly

━━━ HEADER / DETAIL (PARENT / CHILD) MODELING ━━━━━━━━━━━━━━━━━━━━━━━━━━━

Many SMB sources have parent/child structures: invoices/invoice_lines,
orders/order_lines, deliveries/delivery_lines, tickets/ticket_replies,
opportunities/quote_items, etc. The temptation is to model only the
child fact and link to the parent via a technical FK (e.g. an
invoice_id GUID on fact_sales_invoice_lines pointing at
fact_sales_invoices). DO NOT do this alone — it leaves the child
fact unable to answer "which {parent} contains X?" without forcing a
JOIN whose only purpose is recovering a human-readable identifier.

RULES:

1. **Model both parent and child as separate fact tables** at their
   respective grains when both exist in the source.

2. **DENORMALIZE the parent's natural business identifier onto every
   child row** as a degenerate dimension. If the source has
   invoices.invoice_number and invoice_lines.invoice_id, the child
   fact MUST carry invoice_number (column_role: 'degenerate_dimension')
   — JOINed in during the transformation_sql from the parent table.
   Same for invoice_date, customer_key, supplier_key, and any other
   commonly-sliced parent attributes.

3. **The child fact must be self-describing at its grain.** A user
   querying "which invoices contain product X" against
   fact_sales_invoice_lines should get back recognisable invoice
   numbers WITHOUT joining to the header fact.

4. The technical parent FK (e.g. invoice_id GUID) still goes on the
   child fact (for explicit JOINs when needed) — but it MUST be
   marked is_technical: true so it never reaches end users.

WHAT THIS LOOKS LIKE IN A FACT'S COLUMNS:

  fact_sales_invoice_lines:
    invoice_id           UUID    (FK to header, is_technical: true)
    invoice_number       TEXT    (denormalized from header, degenerate_dimension, is_technical: false)
    invoice_date         DATE    (denormalized from header, is_technical: false)
    customer_key         INTEGER (FK to dim_customer, is_technical: true)
    line_no              INTEGER (the lines own grain identifier, is_technical: false)
    product_key          INTEGER (FK to dim_product, is_technical: true)
    quantity             DECIMAL (measure)
    unit_price           DECIMAL (measure)
    line_revenue         DECIMAL (measure)

This applies to EVERY parent/child relationship discovered in the
source, not just invoices.

━━━ TECHNICAL vs BUSINESS COLUMNS (is_technical flag) ━━━━━━━━━━━━━━━━━━━

Every column you design carries an is_technical: boolean flag. The
flag is the firewall that keeps system-generated identifiers from
leaking into chat results, narratives, and sample previews. The
column remains available for JOINs in NL→SQL — it is hidden, not
deleted.

Set is_technical: true when:
  - The column is a UUID/GUID-shaped identifier from the source (e.g.
    ExactOnlines account_id, Salesforce-style 0064x... IDs). The
    user knows the entity by name, not by GUID.
  - The column is a surrogate FK key with _key suffix in a fact
    (e.g. customer_key, product_key, account_key).
  - The column is internal infrastructure (_row_hash, _valid_from,
    _is_current, ...).

Set is_technical: false (the default) when:
  - The column is a business-meaningful natural key the user would
    recognise: invoice_number, order_number, customer_code, sku,
    iban, vat_number, tracking_number, email, etc.
  - All measures, attributes, dates, descriptions.
  - Degenerate dimensions (line_no, etc.).

**Rule of thumb:** would a non-data person at this business recognise
the value as something they'd say out loud to identify the thing?
("INV-2024-0123" yes; "f8706af1-74cf-450c-..." no). If yes →
is_technical=false. If it is a system-generated identifier nobody
says out loud → is_technical=true.

━━━ BUSINESS-FRIENDLY DESCRIPTIONS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Your audience is a business owner, not a data engineer. All display_name and description fields must be written in plain business English.

**Table display_name:**
- Use plain business English, Title Case — never include "dim_", "fact_", or underscores
- Strip technical prefixes: "dim_article" → "Products", "dim_leverancier" → "Suppliers"
- Translate non-English names to English: "dim_klant" → "Customers", "fact_bestelling" → "Orders"
- Use the business concept, not the database name: "Article Dimension" → "Product Catalog"

**Table description:**
- Start with "Your..." or "Contains your..." to make it personal and relatable
- Describe the business purpose, not the technical structure
- NEVER use: "dimension", "fact table", "entity", "surrogate", "normalized", "denormalized", "schema", "cardinality"
- For fact tables, include the grain in business language (e.g., "Your purchase orders — one line for each product ordered.")
- Keep it to one or two sentences
- Examples:
  - BAD: "Transaction fact table recording purchase order line items with quantities and amounts."
  - GOOD: "Your purchase orders — what you bought, how much, and from whom."
  - BAD: "Slowly changing dimension for article master data."
  - GOOD: "Your product catalog with categories, pricing, and VAT details."

**Column description:**
- Describe the business value, not the technical role
- NEVER use: "Primary key", "Foreign key", "Surrogate key", "Index", "Nullable"
- Use instead: "Unique identifier for...", "Links to...", "The date when...", "Which supplier..."
- Keep it under 15 words
- Examples:
  - BAD: "Surrogate key for the customer dimension"
  - GOOD: "Unique identifier for each customer"
  - BAD: "Foreign key to dim_article"
  - GOOD: "Links to the product this line item is for"

━━━ DuckDB SQL RULES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Each table needs a standalone SELECT statement (no CREATE TABLE).

- Dimensions (dag_order=0) execute FIRST; facts (dag_order=1) execute SECOND
- Dimension SQL: ROW_NUMBER() OVER (ORDER BY natural_key) AS {entity}_key, then attributes
- Fact SQL: JOIN to materialized dims to resolve natural keys → surrogate keys
- ALWAYS use TRY_CAST (not CAST) for type conversions — source data has 'None', 'null', '', 'N/A'
- Use NULLIF(TRIM(col), '') before TRY_CAST for string columns
- strftime(value, format) — DuckDB arg order
- extract(year FROM col), extract(month FROM col)

━━━ TABLE REFERENCES — USE DBT MACROS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

All table references inside transformation_sql MUST use dbt macros. This is
required for the new execution engine — lineage and dependency resolution
break without them.

1. **Source-layer tables** (raw ingested tables from the upstream source):
   \`\`\`
   FROM {{ source('source_layer', 'customers') }}
   \`\`\`
   Use this for every table listed in the "SOURCE SCHEMA" section above.

2. **Sibling product tables** (dimensions you are generating in THIS schema,
   referenced from facts):
   \`\`\`
   JOIN {{ ref('dim_customer') }} dc ON ...
   \`\`\`
   Use this whenever a fact table joins to a dimension also being built in
   this schema. dbt uses these refs to order the DAG automatically — that's
   why dag_order + ref() together are how execution order is determined.

3. **Shared/conformed dims from OTHER products** (only if the context
   explicitly lists them as shared dims):
   \`\`\`
   JOIN {{ source('shared_dims', 'dim_customer') }} dc ON ...
   \`\`\`

**DO NOT** use bare table names like \`FROM customers\` or \`JOIN dim_customer\`
— the macro form is mandatory. Bare refs will compile but break lineage.

**DO NOT** alias the macro in a way that creates parsing ambiguity —
always put the alias immediately after \`}}\`:
   \`\`\`
   FROM {{ source('source_layer', 'orders') }} o
   \`\`\`

━━━ OUTPUT FORMAT — Return ONLY valid JSON ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{
  "star_schema": {
    "name": "...",
    "description": "...",
    "grain": "One row per ...",
    "fact_table_type": "transaction",
    "tables": [
      {
        "table_name": "dim_customer",
        "display_name": "Customers",
        "description": "Your customers — everyone who has placed an order.",
        "table_role": "dimension",
        "dag_order": 0,
        "transformation_sql": "SELECT ROW_NUMBER() OVER (ORDER BY c.customer_id) AS customer_key, c.customer_id, c.name, g.group_name FROM {{ source('source_layer', 'customers') }} c LEFT JOIN {{ source('source_layer', 'customer_groups') }} g ON c.group_id = g.id",
        "columns": [{
          "column_name": "customer_key",
          "data_type": "INTEGER",
          "display_name": "Customer Key",
          "description": "Unique identifier for each customer",
          "column_role": "surrogate_key",
          "fk_target_table": null,
          "fk_target_column": null,
          "is_technical": true,
          "transformation_expression": "ROW_NUMBER() OVER (ORDER BY ...)",
          "additivity": null,
          "scd_type": 1,
          "sort_order": 0,
          "lineage": [{"source_table_name": "...", "source_column_name": "...", "transformation_description": "..."}]
        }]
      },
      {
        "table_name": "fact_sales",
        "display_name": "Sales",
        "description": "Your sales transactions — one line for each product sold.",
        "table_role": "fact",
        "dag_order": 1,
        "transformation_sql": "SELECT COALESCE(dc.customer_key, -1) AS customer_key, s.order_id, s.line_total FROM {{ source('source_layer', 'orders') }} s LEFT JOIN {{ ref('dim_customer') }} dc ON s.customer_id = dc.customer_id",
        "columns": [...]
      }
    ],
    "relationships": [
      {"from_table_name": "fact_sales", "from_column_name": "customer_key", "to_table_name": "dim_customer", "to_column_name": "customer_key", "relationship_type": "fact_to_dim"}
    ]
  },
  "proposed_kpis": [
    {"name": "Total Revenue", "description": "...", "formula_plain_text": "...", "formula_sql": "SUM(fact_sales.line_total)", "additivity": "additive"}
  ],
  "dim_date_range": {"start": "2020-01-01", "end": "2027-12-31"}
}`;
}

export function buildStarSchemaDesignUser(
  dataProductName: string,
  dataProductDescription: string,
  _sourceTablesContext: string,  // now in system prompt
): string {
  return `Design a Kimball star schema with DuckDB transformation SQL for:

Data Product: "${dataProductName}"
Description: ${dataProductDescription || 'Infer from source tables'}

Rules reminder:
- Exactly 1 star schema, 1-3 fact tables if needed, max 10 tables total
- Do NOT include dim_date (auto-generated)
- Use ONLY the exact source column names from the schema above
- Include transformation_sql for every table
- Fact SQL must JOIN to dims for surrogate key resolution
- ALL table references in transformation_sql must use {{ source('source_layer', 'name') }}
  for raw source tables or {{ ref('name') }} for sibling product tables`;
}

// ---------------------------------------------------------------------------
// Column Edit (surgical) — unchanged
// ---------------------------------------------------------------------------

export const COLUMN_EDIT_SYSTEM =
`You are a DuckDB SQL expert. The user wants to modify a single column's transformation expression in a star schema table. Return ONLY the updated transformation_expression — nothing else, no JSON wrapping, no explanation.

Rules:
- Output must be a valid DuckDB SQL expression
- It will be used inside a SELECT clause: SELECT {your_expression} AS {column_name}
- Use DuckDB syntax: strftime(col, fmt), CAST, extract, ILIKE, TRY_CAST, etc.
- Do NOT use SQLite functions`;

export function buildColumnEditUser(
  columnName: string,
  currentExpression: string,
  editRequest: string,
  tableContext: string,
): string {
  return `Column: ${columnName}
Current expression: ${currentExpression}
Table context: ${tableContext}

User's edit request: "${editRequest}"

Return ONLY the updated SQL expression.`;
}

// ---------------------------------------------------------------------------
// dim_date template — hardcoded, never AI-generated
// ---------------------------------------------------------------------------

export const DIM_DATE_SQL = (start: string, end: string) => `SELECT
  TRY_CAST(strftime(d, '%Y%m%d') AS INTEGER) AS date_key,
  d::DATE AS full_date,
  extract(year FROM d)::INTEGER AS year,
  extract(quarter FROM d)::INTEGER AS quarter,
  extract(month FROM d)::INTEGER AS month,
  strftime(d, '%B') AS month_name,
  extract(isodow FROM d)::INTEGER AS day_of_week,
  strftime(d, '%A') AS day_name,
  CASE WHEN extract(isodow FROM d) IN (6,7) THEN true ELSE false END AS is_weekend,
  extract(year FROM d)::INTEGER AS fiscal_year,
  extract(quarter FROM d)::INTEGER AS fiscal_quarter
FROM generate_series(DATE '${start}', DATE '${end}', INTERVAL '1 day') AS t(d)`;

export const DIM_DATE_COLUMNS: ColumnDesign[] = [
  { column_name: 'date_key', data_type: 'INTEGER', display_name: 'Date Key', description: 'Surrogate key (YYYYMMDD)', column_role: 'surrogate_key', transformation_expression: "TRY_CAST(strftime(d, '%Y%m%d') AS INTEGER)", scd_type: 1, sort_order: 0, lineage: [{ source_table_name: 'generated', source_column_name: 'calendar_spine', transformation_description: 'Generated — calendar spine' }] },
  { column_name: 'full_date', data_type: 'DATE', display_name: 'Date', description: 'Full calendar date', column_role: 'natural_key', transformation_expression: "d::DATE", scd_type: 1, sort_order: 1, lineage: [{ source_table_name: 'generated', source_column_name: 'calendar_spine', transformation_description: 'Generated — calendar spine' }] },
  { column_name: 'year', data_type: 'INTEGER', display_name: 'Year', description: 'Calendar year', column_role: 'attribute', transformation_expression: "extract(year FROM d)::INTEGER", scd_type: 1, sort_order: 2, lineage: [{ source_table_name: 'generated', source_column_name: 'calendar_spine', transformation_description: 'Generated — calendar spine' }] },
  { column_name: 'quarter', data_type: 'INTEGER', display_name: 'Quarter', description: 'Calendar quarter (1-4)', column_role: 'attribute', transformation_expression: "extract(quarter FROM d)::INTEGER", scd_type: 1, sort_order: 3, lineage: [{ source_table_name: 'generated', source_column_name: 'calendar_spine', transformation_description: 'Generated — calendar spine' }] },
  { column_name: 'month', data_type: 'INTEGER', display_name: 'Month', description: 'Month number (1-12)', column_role: 'attribute', transformation_expression: "extract(month FROM d)::INTEGER", scd_type: 1, sort_order: 4, lineage: [{ source_table_name: 'generated', source_column_name: 'calendar_spine', transformation_description: 'Generated — calendar spine' }] },
  { column_name: 'month_name', data_type: 'VARCHAR', display_name: 'Month Name', description: 'Full month name', column_role: 'attribute', transformation_expression: "strftime(d, '%B')", scd_type: 1, sort_order: 5, lineage: [{ source_table_name: 'generated', source_column_name: 'calendar_spine', transformation_description: 'Generated — calendar spine' }] },
  { column_name: 'day_of_week', data_type: 'INTEGER', display_name: 'Day of Week', description: 'ISO day of week (1=Mon, 7=Sun)', column_role: 'attribute', transformation_expression: "extract(isodow FROM d)::INTEGER", scd_type: 1, sort_order: 6, lineage: [{ source_table_name: 'generated', source_column_name: 'calendar_spine', transformation_description: 'Generated — calendar spine' }] },
  { column_name: 'day_name', data_type: 'VARCHAR', display_name: 'Day Name', description: 'Full day name', column_role: 'attribute', transformation_expression: "strftime(d, '%A')", scd_type: 1, sort_order: 7, lineage: [{ source_table_name: 'generated', source_column_name: 'calendar_spine', transformation_description: 'Generated — calendar spine' }] },
  { column_name: 'is_weekend', data_type: 'BOOLEAN', display_name: 'Weekend?', description: 'True if Saturday or Sunday', column_role: 'attribute', transformation_expression: "CASE WHEN extract(isodow FROM d) IN (6,7) THEN true ELSE false END", scd_type: 1, sort_order: 8, lineage: [{ source_table_name: 'generated', source_column_name: 'calendar_spine', transformation_description: 'Generated — calendar spine' }] },
  { column_name: 'fiscal_year', data_type: 'INTEGER', display_name: 'Fiscal Year', description: 'Fiscal year (same as calendar)', column_role: 'attribute', transformation_expression: "extract(year FROM d)::INTEGER", scd_type: 1, sort_order: 9, lineage: [{ source_table_name: 'generated', source_column_name: 'calendar_spine', transformation_description: 'Generated — calendar spine' }] },
  { column_name: 'fiscal_quarter', data_type: 'INTEGER', display_name: 'Fiscal Quarter', description: 'Fiscal quarter (same as calendar)', column_role: 'attribute', transformation_expression: "extract(quarter FROM d)::INTEGER", scd_type: 1, sort_order: 10, lineage: [{ source_table_name: 'generated', source_column_name: 'calendar_spine', transformation_description: 'Generated — calendar spine' }] },
];
